services:
  - type: web
    name: the-flip
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn the_flip.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: the-flip.onrender.com
      - key: PYTHON_VERSION
        value: 3.13.2
